// NOTE: shares the render contract with apps/wholesale-ui's component of the same
// name (one source of truth for how this renders). Kept as a wealth-local copy to
// keep this a wealth-render-only change; a future pass can consolidate both into
// apps/shared/ui/. Do not let the two drift.
/**
 * Provenance badge component.
 *
 * Provenance is visible, not hidden. The novice should see exactly
 * which SHACL shape validated a signal and which R2RML mapping
 * produced the underlying triple. This is what makes ATLAS auditable.
 */

import React from "react";

interface ProvenanceBadgeProps {
  validatedBy?: string;
  derivedFrom?: string;
  generatedBy?: string;
}

/**
 * Extracts the local name from a URI or path for compact display.
 * "atlas:WealthSignalTypeShape" → "WealthSignalTypeShape"
 * "pattern_a_iceberg/customer-master.r2rml.ttl" → "customer-master.r2rml"
 */
function compactLabel(value: string): string {
  if (!value) return "";
  // Handle URIs with # or /
  const afterHash = value.split("#").pop() || value;
  const afterSlash = afterHash.split("/").pop() || afterHash;
  // Remove .ttl extension for mapping paths
  return afterSlash.replace(/\.ttl$/, "");
}

export function ProvenanceBadge({
  validatedBy,
  derivedFrom,
  generatedBy,
}: ProvenanceBadgeProps) {
  const parts: string[] = [];
  if (validatedBy) parts.push(compactLabel(validatedBy));
  if (derivedFrom) parts.push(compactLabel(derivedFrom));

  if (parts.length === 0) return null;

  return (
    <span
      className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium"
      style={{
        backgroundColor: "var(--color-provenance-bg)",
        borderColor: "var(--color-provenance-border)",
        color: "var(--color-provenance-text)",
        border: "1px solid var(--color-provenance-border)",
      }}
      title={`Validated by: ${validatedBy || "—"}\nDerived from: ${derivedFrom || "—"}\nGenerated by: ${generatedBy || "—"}`}
    >
      <span aria-hidden="true">◈</span>
      {parts.join(" · ")}
    </span>
  );
}
