/**
 * Provenance line component.
 *
 * Provenance is visible, not hidden. The novice should see exactly which SHACL
 * shape validated a signal and which R2RML mapping produced the underlying
 * triple. This is what makes ATLAS auditable — rendered as the monospace
 * `validatedBy … · derivedFrom …` line beneath each signal.
 */

import React from "react";

interface ProvenanceBadgeProps {
  validatedBy?: string;
  derivedFrom?: string;
  generatedBy?: string;
}

/**
 * Extracts the local name from a URI or path for compact display.
 * "atlas:WealthSignalTypeShape" → "WealthSignalTypeShape"
 * "pattern_a_iceberg/customer-master.r2rml.ttl" → "customer-master.r2rml"
 */
function compactLabel(value: string): string {
  if (!value) return "";
  const afterHash = value.split("#").pop() || value;
  const afterSlash = afterHash.split("/").pop() || afterHash;
  return afterSlash.replace(/\.ttl$/, "");
}

export function ProvenanceBadge({
  validatedBy,
  derivedFrom,
  generatedBy,
}: ProvenanceBadgeProps) {
  const hasAny = validatedBy || derivedFrom || generatedBy;
  if (!hasAny) return null;

  return (
    <p
      className="prov"
      title={`Validated by: ${validatedBy || "—"}\nDerived from: ${derivedFrom || "—"}\nGenerated by: ${generatedBy || "—"}`}
    >
      <span aria-hidden="true" className="gem">
        ◈
      </span>
      {validatedBy && (
        <span>
          <b>validatedBy</b> {compactLabel(validatedBy)}
        </span>
      )}
      {derivedFrom && (
        <span>
          <b>· derivedFrom</b> {compactLabel(derivedFrom)}
        </span>
      )}
      {generatedBy && (
        <span>
          <b>· generatedBy</b> {compactLabel(generatedBy)}
        </span>
      )}
    </p>
  );
}
