/**
 * Themes page — market and portfolio themes for the advisor's morning briefing.
 *
 * Themes are curated upstream and summarized by the theme-summarizer agent.
 * The corpus is empty today, so this page renders the real (currently empty)
 * themes query — an honest empty state rather than invented themes. It
 * demonstrates a Phase 2 capability the Wholesale UI does not have.
 */

"use client";

import React from "react";
import { useQuery } from "@apollo/client";
import { THEMES_QUERY } from "../../graphql/queries";
import { ThemeCard } from "../../components/theme-card";
import { AppShell } from "../../../../shared/ui/chrome";

const NAV = [
  { href: "/", label: "My clients" },
  { href: "/conversations", label: "Ask the graph" },
  { href: "/themes", label: "Themes" },
];

export default function ThemesPage() {
  const { data, loading } = useQuery(THEMES_QUERY, {
    variables: { limit: 10 },
  });

  const themes = data?.themes ?? [];

  return (
    <AppShell brandSuffix="Wealth" navLinks={NAV}>
      <div className="page-head">
        <h1>Market themes</h1>
        <p className="sub">Summaries generated by theme-summarizer · probabilistic · informational only</p>
      </div>

      {loading && <p className="loading-line">Loading themes…</p>}

      {!loading && themes.length === 0 && (
        <div className="card">
          <p className="empty">
            No themes tracked yet — the theme corpus is empty; nothing is invented to fill it.
            Once curated themes are loaded, theme-summarizer&apos;s summaries appear here.
          </p>
        </div>
      )}

      {themes.length > 0 && (
        <div className="entity-grid">
          {themes.map((theme: any) => (
            <ThemeCard key={theme.uri} theme={theme.themeLabel} summary={theme.summary} />
          ))}
        </div>
      )}
    </AppShell>
  );
}
