/**
 * Themes page — market and portfolio themes for the advisor's morning briefing.
 *
 * Themes are curated upstream and summarized by the theme-summarizer agent.
 * This page demonstrates a Phase 2 capability that the Wholesale UI does not have.
 */

"use client";

import React from "react";
import { useQuery } from "@apollo/client";
import { THEMES_QUERY } from "../../graphql/queries";
import { ThemeCard } from "../../components/theme-card";
import { useAuth } from "../../../../shared/auth/use-auth";

export default function ThemesPage() {
  const { personaClaim } = useAuth();
  const { data, loading } = useQuery(THEMES_QUERY, {
    variables: { limit: 10 },
  });

  const themes = data?.themes ?? [];

  return (
    <main className="p-6">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold">Market themes</h1>
        <p className="text-sm text-neutral-400">
          Summaries generated by theme-summarizer · probabilistic · informational only
        </p>
      </header>

      {loading && <p className="text-neutral-400">Loading themes...</p>}

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {themes.map((theme: any) => (
          <ThemeCard
            key={theme.uri}
            theme={theme.themeLabel}
            summary={theme.summary}
          />
        ))}
      </div>
    </main>
  );
}
